[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/results"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/diagnostic"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

